# ========================================
# API Automation Framework - Environment Config
# ========================================

# Base URLs for different environments
base.url.dev=https://petstore.swagger.io/v2
base.url.qa=https://petstore.swagger.io/v2
base.url.prod=https://petstore.swagger.io/v2

# Current environment to run tests (dev / qa / prod)
env=dev

