#User Model

#Environmant 
env=dev

# Base URLs
base.url.dev = https://petstore.swagger.io/v2
base.url.qa = https://petstore-qa.example.com/v2
base.url.prod = https://petstore-prod.example.com/v2

# User endpoints

user.post = /user
user.get = /user/{username}
user.update = /user/{username}
user.delete = /user/{username}

#post_url = https://petstore.swagger.io/v2/user
#get_url = https://petstore.swagger.io/v2/user/{username}
#update_url = https://petstore.swagger.io/v2/user/{username}
#delete_url = https://petstore.swagger.io/v2/user/{username}
